### ISSUE TITLE
 timing for MegaCam

### ISSUE THREAD

**Issue by ijiraq** [OSSOS/MOP#346]
There was a change of the controllers for MP during the April run.   Information below... we’ll need to adjust how the stepZjmp works. 

Begin forwarded message:

From: Richard Wainscoat <rjw@IfA.Hawaii.Edu>
Subject: Fwd: timing for MegaCam
Date: May 21, 2015 at 10:13:58 AM EDT
To: "Kavelaars, JJ" <JJ.Kavelaars@nrc-cnrc.gc.ca>

Here is our best knowledge of Megcam timing at this time.  The change occurred in April 2015.

Richard

Begin forwarded message:

From: Richard Wainscoat <rjw@ifa.hawaii.edu>
Subject: Fwd: timing for MegaCam
Date: April 24, 2015 at 7:23:09 PM EDT
To: David Tholen <tholen@ifa.hawaii.edu>

Looks like the midpoint of the exposure is now UTCEND - 0.73 sec - (exposure time  / 2  )     Wobble on the 0.73 sec is +/- 0.15 sec.

Finally making progress.

Richard

**Comment by jmpetit** [comment]
Question: How is it currently done in stepZjmp ?
Answer: uses MJD-OBS + EXPTIME/2

Question: Was that valid ?

Question: Is it still valid ?

**Comment by ijiraq** [comment]
Hi, I've double checked this.  

mopheader contains the value:  

MJD-OBSC = MJD-OBS + exptime/2.0 


RW claims:

MJD-OBSC = DATE-OBS + UTCEND - 0.73s - exptime/2.0

those to approaches differ by ~50s for exposure 1785787

RW's value is based on NEO tracking.  We could not notice that level of difference.  likely they are correct.

**Comment by mtbannister** [comment]
Hurrah, no recompiling binaries!

**Comment by mtbannister** [comment]
So we are still 49 sec incorrect on the observation midpoint, but only in the mopheader, and so the pipeline does not need alteration for the purposes of TNOs?

**Comment by ijiraq** [comment]
I'm checking with RW about the pre-April computation that PS uses. 

We should fix all our times as the occultation team thinks time is important.
