### ISSUE TITLE
[orbfit] Distance needs to update when predict made

### ISSUE THREAD

**Issue by mtbannister** [OSSOS/MOP#353]
The call to predict() only gives sky position. Should work in an additional call to fit_radec: use that predicted sky position as a proxy sky coordinate to run another round of orbit fitting and give an updated barycentric distance. 
At present the barycentric distance given by str() doesn't update, which is a bit deceptive.

**Comment by ijiraq** [comment]
Resolved in latest release of mp_ephem  (which is now the home of this stuff, external to OSSOS/MOP)
